using System.Text;
using KarazhanAddonStudio.Models;

namespace KarazhanAddonStudio.Services;

public static class LuaExporter
{
    public static string Export(LayoutDocument document)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by KarazhanAddonStudio");
        sb.AppendLine("local addonName = ...");
        sb.AppendLine();
        sb.AppendLine(
            $"local Root = CreateFrame(\"Frame\", \"{document.Name}Frame\", UIParent)");
        sb.AppendLine($"Root:SetSize({document.Width}, {document.Height})");
        sb.AppendLine(
            "Root:SetPoint(\"CENTER\", UIParent, \"CENTER\", 0, 0)");
        sb.AppendLine("Root:Hide()");
        sb.AppendLine();

        foreach (var widget in document.Widgets.OrderBy(w => w.Top).ThenBy(w => w.Left))
        {
            var name = Sanitize(widget.Name);
            sb.AppendLine($"-- {widget.Name}");
            switch (widget.Kind)
            {
            case WidgetKind.Panel:
                sb.AppendLine(
                    $"local {name} = CreateFrame(\"Frame\", nil, Root)");
                sb.AppendLine(
                    $"{name}:SetPoint(\"TOPLEFT\", Root, \"TOPLEFT\", {widget.Left}, -{widget.Top})");
                sb.AppendLine(
                    $"{name}:SetSize({widget.Width}, {widget.Height})");
                break;
            case WidgetKind.Button:
                sb.AppendLine(
                    $"local {name} = CreateFrame(\"Button\", nil, Root, \"UIPanelButtonTemplate\")");
                sb.AppendLine(
                    $"{name}:SetPoint(\"TOPLEFT\", Root, \"TOPLEFT\", {widget.Left}, -{widget.Top})");
                sb.AppendLine(
                    $"{name}:SetSize({widget.Width}, {widget.Height})");
                sb.AppendLine($"{name}:SetText(\"{Escape(widget.Text)}\")");
                break;
            case WidgetKind.ProgressBar:
                sb.AppendLine(
                    $"local {name} = CreateFrame(\"Frame\", nil, Root)");
                sb.AppendLine(
                    $"{name}:SetPoint(\"TOPLEFT\", Root, \"TOPLEFT\", {widget.Left}, -{widget.Top})");
                sb.AppendLine(
                    $"{name}:SetSize({widget.Width}, {widget.Height})");
                sb.AppendLine(
                    $"local {name}Texture = {name}:CreateTexture(nil, \"ARTWORK\")");
                sb.AppendLine(
                    $"{name}Texture:SetAllPoints({name})");
                sb.AppendLine(
                    $"{name}Texture:SetTexture(\"Interface\\\\TARGETINGFRAME\\\\UI-StatusBar\")");
                break;
            default:
                sb.AppendLine(
                    $"local {name} = Root:CreateFontString(nil, \"OVERLAY\", \"GameFontNormal\")");
                sb.AppendLine(
                    $"{name}:SetPoint(\"TOPLEFT\", Root, \"TOPLEFT\", {widget.Left}, -{widget.Top})");
                sb.AppendLine(
                    $"{name}:SetWidth({widget.Width})");
                sb.AppendLine($"{name}:SetText(\"{Escape(widget.Text)}\")");
                break;
            }

            if (!string.IsNullOrWhiteSpace(widget.BindingKey))
                sb.AppendLine($"-- binding: {widget.BindingKey}");

            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string Sanitize(string name)
    {
        var chars = name.Where(char.IsLetterOrDigit).ToArray();
        return chars.Length == 0 ? "Widget" : new string(chars);
    }

    private static string Escape(string text)
    {
        return text.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
